version: '3.9'
services:
db:
image: postgres:15
container_name: my-postgres-new
environment:
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_DB: ${POSTGRES_DB}
volumes:
- pgdata:/var/lib/postgresql/data
ports:
- "5433:5432"


web:
image: your_dockerhub_user/fastapi-app:${TAG:-latest}
container_name: fastapi-app
env_file:
- .env
depends_on:
- db
ports:
- "8000:8000"


volumes:
pgdata: